### PR TITLE
FIX: base model as key not allowed

### PR DESCRIPTION
**Pull request by Segelzwerg**

### CODE REVIEW

**Comment by iTitus** [comment]
We could still have a dict, but with player names as keys. What do you think?

**Comment by Segelzwerg** [comment]
> We could still have a dict, but with player names as keys. What do you think?

Yes tried that first and it is messy, because you still need the players object somewhere. You will end with a deep nested dict. I think an entry object ist much cleaner

**Comment by iTitus** [comment]
> 
> 
> > We could still have a dict, but with player names as keys. What do you think?
> 
> Yes tried that first and it is messy, because you still need the players object somewhere. You will end with a deep nested dict. I think an entry object ist much cleaner

Keep the Entry Object and do a Dict of Name[String] -> Entry.
you can still use `values()` to iterate over all entries.

**Comment by Segelzwerg** [comment]
> > 
> > 
> > > We could still have a dict, but with player names as keys. What do you think?
> > 
> > Yes tried that first and it is messy, because you still need the players object somewhere. You will end with a deep nested dict. I think an entry object ist much cleaner
> 
> Keep the Entry Object and do a Dict of Name[String] -> Entry.
> you can still use `values()` to iterate over all entries.

Sounds good

**Comment by Segelzwerg** [comment]
> > > We could still have a dict, but with player names as keys. What do you think?
> > 
> > 
> > Yes tried that first and it is messy, because you still need the players object somewhere. You will end with a deep nested dict. I think an entry object ist much cleaner
> 
> Keep the Entry Object and do a Dict of Name[String] -> Entry. you can still use `values()` to iterate over all entries.

I updated it to use `dict` again. Can you review it again?

**Review by iTitus — APPROVED** [review]

**Pull request merged**
